# Generated by Django 5.2.7 on 2025-10-25 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCIE10',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE-10',
                'verbose_name_plural': 'Diagnósticos CIE-10',
                'db_table': 'DiagnosticoCIE10',
            },
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ficha_clinica_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rut_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rut_encrypted', models.TextField(blank=True, null=True)),
                ('nombre_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_encrypted', models.TextField(blank=True, null=True)),
                ('telefono_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_encrypted', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('pertenece_pueblo_originario', models.BooleanField(default=False)),
                ('prevision', models.CharField(blank=True, choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'PARTICULAR'), ('NINGUNA', 'NINGUNA')], max_length=50, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
                'db_table': 'Madre',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_parto', models.DateTimeField()),
                ('edad_gestacional', models.IntegerField(blank=True, null=True)),
                ('tipo_parto', models.CharField(choices=[('Eutócico', 'Eutócico'), ('Cesárea Electiva', 'Cesárea Electiva'), ('Cesárea Urgencia', 'Cesárea Urgencia'), ('Fórceps', 'Fórceps'), ('Vacuum', 'Vacuum')], max_length=50)),
                ('anestesia', models.CharField(blank=True, choices=[('Epidural', 'Epidural'), ('Raquídea', 'Raquídea'), ('General', 'General'), ('Otra', 'Otra'), ('Ninguna', 'Ninguna')], max_length=50, null=True)),
                ('partograma_data', models.JSONField(blank=True, null=True)),
                ('epicrisis_data', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='core.madre')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'Parto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=255, unique=True)),
                ('nombre_completo', models.TextField()),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut_provisorio', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_al_nacer', models.CharField(choices=[('Vivo', 'Vivo'), ('Nacido Muerto', 'Nacido Muerto')], max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indeterminado', 'Indeterminado')], max_length=50, null=True)),
                ('peso_gramos', models.IntegerField(blank=True, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('apgar_1_min', models.SmallIntegerField(blank=True, null=True)),
                ('apgar_5_min', models.SmallIntegerField(blank=True, null=True)),
                ('profilaxis_vit_k', models.BooleanField(blank=True, null=True)),
                ('profilaxis_oftalmica', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='core.parto')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos_registrados', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'db_table': 'RecienNacido',
            },
        ),
        migrations.AddField(
            model_name='parto',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos_registrados', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id_uuid', models.UUIDField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('ip_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'LogAuditoria',
            },
        ),
        migrations.CreateModel(
            name='DocumentoReferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mongodb_object_id', models.CharField(max_length=255, unique=True)),
                ('nombre_archivo', models.TextField()),
                ('tipo_documento', models.CharField(choices=[('EPICRISIS_PDF', 'Epicrisis PDF'), ('REPORTE_EXCEL', 'Reporte Excel'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_referencia', to='core.parto')),
                ('usuario_generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_generados', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Referencia de Documento',
                'verbose_name_plural': 'Referencias de Documentos',
                'db_table': 'DocumentoReferencia',
            },
        ),
        migrations.CreateModel(
            name='PartoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticocie10')),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parto')),
            ],
            options={
                'verbose_name': 'Parto-Diagnóstico',
                'verbose_name_plural': 'Partos-Diagnósticos',
                'db_table': 'PartoDiagnostico',
                'unique_together': {('parto', 'diagnostico')},
            },
        ),
        migrations.CreateModel(
            name='Defuncion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_defuncion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('causa_defuncion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defunciones', to='core.diagnosticocie10')),
                ('madre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defuncion', to='core.madre')),
                ('recien_nacido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defuncion', to='core.reciennacido')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defunciones_registradas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Defunción',
                'verbose_name_plural': 'Defunciones',
                'db_table': 'Defuncion',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recien_nacido__isnull', False), ('madre__isnull', True)), models.Q(('recien_nacido__isnull', True), ('madre__isnull', False)), _connector='OR'), name='check_recien_nacido_or_madre')],
            },
        ),
    ]
